name: Build PS3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PS3DEV: /usr/local/ps3dev
      PSL1GHT: /usr/local/ps3dev

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
          git make gcc g++ \
          autoconf automake \
          bison flex \
          libelf-dev \
          zlib1g-dev \
          texinfo \
          libtool \
          libtool-bin \
          libgmp-dev

      - name: Build Toolchain
        run: |
          git clone https://github.com/ps3dev/ps3toolchain.git

          cd ps3toolchain

          chmod +x toolchain.sh

          ./toolchain.sh

      - name: Add PATH
        run: |
          echo "/usr/local/ps3dev/bin" >> $GITHUB_PATH
          echo "/usr/local/ps3dev/ppu/bin" >> $GITHUB_PATH

      - name: Check Tools
        run: |
          which powerpc64-ps3-elf-gcc

          find /usr/local/ps3dev -name "*sprx*" || true
          find /usr/local/ps3dev -name "*prx*" || true

      - name: Build
        run: |
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .
